"""Tests for duho.scaffold: the opt-in launcher-pair generator.

Real launcher files are written under ``tmp_path`` and their **content** is
asserted (the exec line, ``PYTHONPATH`` handling, the ``PYTHON`` override) --
these tests deliberately do NOT spawn a real shell, so they run identically on
every OS. The POSIX executable-bit check is skipped on Windows (``sys.platform``)
where the bit is meaningless.

The emitted launcher text must be generic -- a private-lib name must never leak
into a generated file. ``test_emitted_text_is_generic`` greps the generated
content for the forbidden names.
"""

import stat
import sys

import pytest

import duho
import duho.scaffold as scaffold
from duho.scaffold import ScaffoldCmd, generate_launchers


#: The only project-identifying tokens the generated launcher text is allowed to
#: carry are the *user-supplied* app name and the generic generator marker
#: ``duho`` (in the "Generated by duho.scaffold" comment). The generator must
#: never bake in any predecessor-project name, so rather than blacklist those
#: names here (they must not appear in shipped artifacts either), the guard test
#: asserts the emitted text is generic *positively*: every ASCII "word" in it is
#: either a shell/batch keyword, a generic launcher token, or the app name.
_ALLOWED_LAUNCHER_WORDS = frozenset(
    {
        # generic launcher / generator vocabulary
        "duho", "scaffold", "launcher", "generated", "regenerate", "install",
        "checkout", "source", "runs", "without", "putting", "hand", "editing",
        "honors", "pin", "interpreter", "rather", "than", "resolve", "real",
        "directory", "following", "symlinks", "defined", "off", "echo",
        # shell / batch / python vocabulary
        "sh", "bin", "set", "readlink", "case", "esac", "cd", "dirname", "pwd",
        "export", "exec", "python", "python3", "root", "lib", "src", "link",
        "script", "bindir", "libdir", "pythonpath", "rem", "setlocal",
        "echo", "defined", "for", "in", "do", "done", "while", "then", "else",
        "fi", "if", "not",
        # generic English connective words appearing in the header comments
        "from", "the", "this", "its", "own", "app", "put",
    }
)


def _read(path, *, binary=False):
    """Read a launcher file, preserving its raw bytes/newlines when binary."""
    if binary:
        return path.read_bytes()
    with path.open("r", encoding="utf-8", newline="") as fh:
        return fh.read()


# --------------------------------------------------------------------------
# generate_launchers: what it writes
# --------------------------------------------------------------------------


def test_writes_both_launchers_and_returns_paths(tmp_path):
    """The pair is written into ``bin/`` and both paths are returned."""
    written = generate_launchers("myapp", tmp_path)
    posix = tmp_path / "bin" / "myapp"
    windows = tmp_path / "bin" / "myapp.cmd"
    assert written == [posix, windows]
    assert posix.exists()
    assert windows.exists()


def test_bin_directory_is_auto_created(tmp_path):
    """``bin/`` need not pre-exist -- the generator creates it."""
    assert not (tmp_path / "bin").exists()
    generate_launchers("myapp", tmp_path)
    assert (tmp_path / "bin").is_dir()


def test_posix_launcher_content(tmp_path):
    """POSIX launcher references the app, the libdir on PYTHONPATH, and execs it."""
    generate_launchers("myapp", tmp_path, libdir="lib")
    text = _read(tmp_path / "bin" / "myapp")
    assert text.startswith("#!/bin/sh")
    # PYTHONPATH points at <root>/<libdir> and prepends when already set.
    assert 'libdir="$root/lib"' in text
    assert 'PYTHONPATH="$libdir:$PYTHONPATH"' in text
    assert "export PYTHONPATH" in text
    # The exec line runs `python -m myapp "$@"` and honors $PYTHON.
    assert 'exec "${PYTHON:-python3}" -m myapp "$@"' in text
    # POSIX launcher uses LF newlines only (runs on a POSIX host).
    assert "\r\n" not in text


def test_windows_launcher_content(tmp_path):
    """Windows .cmd references the app, the libdir on PYTHONPATH, and runs it."""
    generate_launchers("myapp", tmp_path, libdir="lib")
    text = _read(tmp_path / "bin" / "myapp.cmd")
    assert text.startswith("@echo off")
    assert 'set "libdir=%root%\\lib"' in text
    assert 'set "PYTHONPATH=%libdir%;%PYTHONPATH%"' in text
    # Runs `%PYTHON% -m myapp %*` and defaults PYTHON when unset.
    assert 'if not defined PYTHON set "PYTHON=python"' in text
    assert '"%PYTHON%" -m myapp %*' in text
    # Windows launcher uses CRLF newlines.
    assert "\r\n" in text


def test_libdir_is_honored(tmp_path):
    """A ``src``-layout app puts ``src`` (not ``lib``) on PYTHONPATH."""
    generate_launchers("myapp", tmp_path, libdir="src")
    posix = _read(tmp_path / "bin" / "myapp")
    windows = _read(tmp_path / "bin" / "myapp.cmd")
    assert 'libdir="$root/src"' in posix
    assert 'set "libdir=%root%\\src"' in windows


def test_python_override_baked_in(tmp_path):
    """An explicit ``python`` becomes the default interpreter in both launchers."""
    generate_launchers("myapp", tmp_path, python="python3.11")
    posix = _read(tmp_path / "bin" / "myapp")
    windows = _read(tmp_path / "bin" / "myapp.cmd")
    assert 'exec "${PYTHON:-python3.11}" -m myapp "$@"' in posix
    assert 'if not defined PYTHON set "PYTHON=python3.11"' in windows


@pytest.mark.skipif(
    sys.platform.startswith("win"),
    reason="POSIX executable bit is meaningless on Windows",
)
def test_posix_launcher_is_executable(tmp_path):
    """On POSIX the generated shell launcher gets its executable bit set."""
    generate_launchers("myapp", tmp_path)
    mode = (tmp_path / "bin" / "myapp").stat().st_mode
    assert mode & stat.S_IXUSR


# --------------------------------------------------------------------------
# Overwrite safety
# --------------------------------------------------------------------------


def test_refuses_to_overwrite_without_flag(tmp_path):
    """A second call without ``overwrite`` refuses (FileExistsError)."""
    generate_launchers("myapp", tmp_path)
    with pytest.raises(FileExistsError):
        generate_launchers("myapp", tmp_path)


def test_overwrite_true_rewrites(tmp_path):
    """``overwrite=True`` rewrites both launchers in place."""
    generate_launchers("myapp", tmp_path, libdir="lib")
    # Re-generate with a different libdir; content must reflect the new value.
    written = generate_launchers("myapp", tmp_path, libdir="src", overwrite=True)
    assert len(written) == 2
    assert 'libdir="$root/src"' in _read(tmp_path / "bin" / "myapp")


def test_overwrite_message_names_the_conflict(tmp_path):
    """The refusal error names the conflicting launcher path."""
    generate_launchers("myapp", tmp_path)
    with pytest.raises(FileExistsError) as excinfo:
        generate_launchers("myapp", tmp_path)
    assert "myapp" in str(excinfo.value)


# --------------------------------------------------------------------------
# Private-lib rule: emitted text must be generic
# --------------------------------------------------------------------------


def test_emitted_text_is_generic(tmp_path):
    """Emitted launchers carry only generic tokens + the user's app name.

    Rather than blacklist predecessor-project names (which must not appear in a
    shipped test either), this asserts genericness *positively*: every ASCII
    alphabetic word of length >= 3 in the generated text is either a known
    launcher/shell/batch keyword (:data:`_ALLOWED_LAUNCHER_WORDS`) or the
    user-supplied app name. Any other identifier would fail the test — so a baked-in
    project name could never slip through unnoticed.
    """
    import re

    app = "widget"
    generate_launchers(app, tmp_path)
    posix = _read(tmp_path / "bin" / app)
    windows = _read(tmp_path / "bin" / (app + ".cmd"), binary=True).decode()

    allowed = _ALLOWED_LAUNCHER_WORDS | {app}
    for label, text in (("POSIX", posix), (".cmd", windows)):
        words = {w.lower() for w in re.findall(r"[A-Za-z]{3,}", text)}
        unexpected = words - allowed
        assert not unexpected, (
            "%s launcher contains unexpected identifier(s) %s -- a non-generic "
            "token leaked into the emitted text" % (label, sorted(unexpected))
        )


# --------------------------------------------------------------------------
# CLI entry (dogfoods duho: ScaffoldCmd is a duho Cli/Cmd)
# --------------------------------------------------------------------------


def test_scaffold_cmd_is_a_duho_cmd():
    """The CLI is implemented as a duho command (Cli subclass of Cmd)."""
    assert issubclass(ScaffoldCmd, duho.Cmd)


def test_cli_writes_pair_and_exits_zero(tmp_path):
    """``duho.main(ScaffoldCmd, ...)`` writes the pair and returns 0."""
    rc = duho.main(
        ScaffoldCmd,
        ["demo", "--root", str(tmp_path), "--libdir", "lib", "--force"],
    )
    assert rc == 0
    assert (tmp_path / "bin" / "demo").exists()
    assert (tmp_path / "bin" / "demo.cmd").exists()
    assert 'exec "${PYTHON:-python3}" -m demo "$@"' in _read(tmp_path / "bin" / "demo")


def test_cli_module_main_entrypoint(tmp_path):
    """The module-level ``main(argv)`` entry dispatches the command too."""
    rc = scaffold.main(["demo", "--root", str(tmp_path), "--force"])
    assert rc == 0
    assert (tmp_path / "bin" / "demo").exists()


def test_cli_force_flag_overwrites(tmp_path):
    """``--force`` on the CLI maps to ``overwrite=True``."""
    scaffold.main(["demo", "--root", str(tmp_path), "--force"])
    # Without --force a second run would refuse; with it, it succeeds (rc 0).
    rc = scaffold.main(["demo", "--root", str(tmp_path), "--force"])
    assert rc == 0


# --------------------------------------------------------------------------
# Opt-in surface
# --------------------------------------------------------------------------


def test_not_on_core_public_surface():
    """``scaffold`` is a dev tool -- not exported on the top-level duho.__all__."""
    assert "scaffold" not in duho.__all__
    assert "generate_launchers" not in duho.__all__


def test_module_all_lists_public_symbols():
    """The module's own ``__all__`` lists its public API."""
    assert set(scaffold.__all__) == {"generate_launchers", "ScaffoldCmd"}
